name: Filter demo workflow

on:
  workflow_dispatch:
paths:
  - 'app/**'

  workflow_dispatch:

jobs:
  filter-check:
    runs-on: ubuntu-latest

    steps:
      - name: show trigger info
        run: echo "workflow tiggered because change is made in app folder"



