name: Self Hosted Runner Demo

on:
  workflow_dispatch:

jobs:
  self-hosted-test:
    runs-on: self-hosted

    steps:
      - name: Show Machine Info
        run: |
          echo "Running on self-hosted runner"
          hostname
          uname -a
